### ISSUE TITLE
There are some dependencies which are forgotten in readme

### ISSUE THREAD

**Issue by yinsp398** [mive93/DAG-scheduling#2]
Eigen3:
sudo apt-get install libeigen3_dev

Python3:
sudo apt-get install python3-dev

TBB:
git clone https://github.com/wjakob/tbb.git
cd tbb && mkdir build && cd build && cmake .. && make && sudo make install

c++ version> c++17

**Comment by mive93** [comment]
I have updated the README, thank you :)
